
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 10 16:50:22 ART 2016
//----------------------------------------------------

package main.lpModel.dtNet.dtnParser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 9;
  public static final int LBRACE = 6;
  public static final int STRING = 8;
  public static final int EOF = 0;
  public static final int RBRACKET = 5;
  public static final int error = 1;
  public static final int NODES = 2;
  public static final int INTERVALS = 3;
  public static final int LBRACKET = 4;
  public static final int RBRACE = 7;
}

